var MongoClient = require('mongodb').MongoClient;
var url = "mongodb+srv://sprintTeam:password1001@cluster0.oq1gf.mongodb.net/Cluster0?retryWrites=true&w=majority";



MongoClient.connect(url, function(err, db) {
    if (err) throw err;
    var dbo = db.db("animaldb");
    var animalobj = [{Animalname :"Eastern grey kangaroo"},
    {"Animal names":"Turkey, australian brush"},
    {"Animal names":"Thrasher, curve-billed"},
    {"Animal names":"Fox, north american red"},
    {"Animal names":"Savannah deer"},
    {"Animal names":"Cockatoo, sulfur-crested"},
    {"Animal names":"Galapagos albatross"},
    {"Animal names":"Albatross, waved"},
    {"Animal names":"Insect, stick"},
    {"Animal names":"Buffalo, african"},
    {"Animal names":"Rattlesnake, dusky"},
    {"Animal names":"Albatross, waved"},
    {"Animal names":"Woodpecker, downy"},
    {"Animal names":"Hummingbird (unidentified)"},
    {"Animal names":"Common zebra"},
    {"Animal names":"Honey badger"},
    {"Animal names":"Southern screamer"},
    {"Animal names":"Deer, roe"},
    {"Animal names":"Dolphin, striped"},
    {"Animal names":"White-bellied sea eagle"},
    {"Animal names":"Squirrel, golden-mantled ground"},
    {"Animal names":"Common boubou shrike"},
    {"Animal names":"Snake, western patch-nosed"},
    {"Animal names":"Coqui francolin"},
    {"Animal names":"Mongoose, banded"},
    {"Animal names":"Spider, wolf"},
    {"Animal names":"House sparrow"},
    {"Animal names":"Phalarope, northern"},
    {"Animal names":"Kite, black"},
    {"Animal names":"Mongoose, eastern dwarf"},
    {"Animal names":"Red meerkat"},
    {"Animal names":"Gull, kelp"},
    {"Animal names":"Green heron"},
    {"Animal names":"Elephant, african"},
    {"Animal names":"Hyrax"},
    {"Animal names":"Black-fronted bulbul"},
    {"Animal names":"Silver-backed fox"},
    {"Animal names":"Roseate cockatoo"},
    {"Animal names":"Bahama pintail"},
    {"Animal names":"Lizard, goanna"},
    {"Animal names":"Red deer"},
    {"Animal names":"Gull, dusky"},
    {"Animal names":"Lechwe, kafue flats"},
    {"Animal names":"Sheep, red"},
    {"Animal names":"Shrike, crimson-breasted"},
    {"Animal names":"Pine snake (unidentified)"},
    {"Animal names":"Koala"},
    {"Animal names":"Grouse, greater sage"},
    {"Animal names":"Kelp gull"},
    {"Animal names":"Frilled dragon"},
    {"Animal names":"Bunting, crested"},
    {"Animal names":"Dove, rock"},
    {"Animal names":"Rat, arboral spiny"},
    {"Animal names":"Eagle, tawny"},
    {"Animal names":"Trumpeter, dark-winged"},
    {"Animal names":"Alligator, american"},
    {"Animal names":"Whale, baleen"},
    {"Animal names":"Brindled gnu"},
    {"Animal names":"Grey mouse lemur"},
    {"Animal names":"Egyptian viper"},
    {"Animal names":"Civet, small-toothed palm"},
    {"Animal names":"Bee-eater, white-fronted"},
    {"Animal names":"Starling, greater blue-eared"},
    {"Animal names":"Greater sage grouse"},
    {"Animal names":"Wallaby, whip-tailed"},
    {"Animal names":"White stork"},
    {"Animal names":"American badger"},
    {"Animal names":"Ring-tailed possum"},
    {"Animal names":"Cat, ringtail"},
    {"Animal names":"Chilean flamingo"},
    {"Animal names":"Skunk, striped"},
    {"Animal names":"European red squirrel"},
    {"Animal names":"Mourning collared dove"},
    {"Animal names":"Puku"},
    {"Animal names":"Silver-backed fox"},
    {"Animal names":"Bustard, denham's"},
    {"Animal names":"Greater adjutant stork"},
    {"Animal names":"Vulture, griffon"},
    {"Animal names":"Avocet, pied"},
    {"Animal names":"Skua, great"},
    {"Animal names":"Weaver, chestnut"},
    {"Animal names":"Lemming, collared"},
    {"Animal names":"Turtle (unidentified)"},
    {"Animal names":"Indian tree pie"},
    {"Animal names":"Dragon, asian water"},
    {"Animal names":"American black bear"},
    {"Animal names":"Grey mouse lemur"},
    {"Animal names":"Whale, long-finned pilot"},
    {"Animal names":"Pig-tailed macaque"},
    {"Animal names":"Racer, blue"},
    {"Animal names":"Macaque, bonnet"},
    {"Animal names":"Swan, black"},
    {"Animal names":"Mongoose, javan gold-spotted"},
    {"Animal names":"Frog (unidentified)"},
    {"Animal names":"Platypus"},
    {"Animal names":"Booby, blue-faced"},
    {"Animal names":"Civet, small-toothed palm"},
    {"Animal names":"Wombat, common"},
    {"Animal names":"Bushbuck"},
    {"Animal names":"Crested porcupine"},
    {"Animal names":"Porcupine, tree"},
    {"Animal names":"Salmon pink bird eater tarantula"},
    {"Animal names":"Jackal, indian"},
    {"Animal names":"Yellow-headed caracara"},
    {"Animal names":"Turkey, australian brush"},
    {"Animal names":"Blue fox"},
    {"Animal names":"Possum, western pygmy"},
    {"Animal names":"Red-shouldered glossy starling"},
    {"Animal names":"Blackbird, red-winged"},
    {"Animal names":"Stanley bustard"},
    {"Animal names":"Dove, laughing"},
    {"Animal names":"Monitor lizard (unidentified)"},
    {"Animal names":"Gerenuk"},
    {"Animal names":"Tsessebe"},
    {"Animal names":"Spotted hyena"},
    {"Animal names":"Possum, common brushtail"},
    {"Animal names":"Great kiskadee"},
    {"Animal names":"Tropical buckeye butterfly"},
    {"Animal names":"Indian jackal"},
    {"Animal names":"Wambenger, red-tailed"},
    {"Animal names":"Madagascar fruit bat"},
    {"Animal names":"Monkey, rhesus"},
    {"Animal names":"Hornbill, red-billed"},
    {"Animal names":"Red-cheeked cordon bleu"},
    {"Animal names":"Four-horned antelope"},
    {"Animal names":"Wildebeest, blue"},
    {"Animal names":"Iguana, land"},
    {"Animal names":"Phalarope, grey"},
    {"Animal names":"Yellow-necked spurfowl"},
    {"Animal names":"Little brown bat"},
    {"Animal names":"Squirrel, malabar"},
    {"Animal names":"Jackal, asiatic"},
    {"Animal names":"Long-necked turtle"},
    {"Animal names":"Red-capped cardinal"},
    {"Animal names":"Common brushtail possum"},
    {"Animal names":"Bent-toed gecko"},
    {"Animal names":"Woolly-necked stork"},
    {"Animal names":"Kinkajou"},
    {"Animal names":"Blackbuck"},
    {"Animal names":"Zorro, azara's"},
    {"Animal names":"Bleeding heart monkey"},
    {"Animal names":"Bird, magnificent frigate"},
    {"Animal names":"Gecko, bent-toed"},
    {"Animal names":"Coqui francolin"},
    {"Animal names":"Common shelduck"},
    {"Animal names":"Flamingo, lesser"},
    {"Animal names":"Lory, rainbow"},
    {"Animal names":"African bush squirrel"},
    {"Animal names":"Thirteen-lined squirrel"},
    {"Animal names":"Feathertail glider"},
    {"Animal names":"Fox, bat-eared"},
    {"Animal names":"Macaque, pig-tailed"},
    {"Animal names":"Langur, hanuman"},
    {"Animal names":"Southern ground hornbill"},
    {"Animal names":"Black-capped chickadee"},
    {"Animal names":"Antelope, roan"},
    {"Animal names":"Alligator, mississippi"},
    {"Animal names":"Colobus, white-mantled"},
    {"Animal names":"Asian foreset tortoise"},
    {"Animal names":"Spurfowl, yellow-necked"},
    {"Animal names":"Ox, musk"},
    {"Animal names":"North American river otter"},
    {"Animal names":"Fox, blue"},
    {"Animal names":"Greater roadrunner"},
    {"Animal names":"Leopard, indian"},
    {"Animal names":"Legaan, Monitor (unidentified)"},
    {"Animal names":"Uinta ground squirrel"},
    {"Animal names":"Rhesus monkey"},
    {"Animal names":"Common long-nosed armadillo"},
    {"Animal names":"Tortoise, radiated"},
    {"Animal names":"Skink, african"},
    {"Animal names":"Brolga crane"},
    {"Animal names":"Gemsbok"},
    {"Animal names":"Coot, red-knobbed"},
    {"Animal names":"Asian elephant"},
    {"Animal names":"Lemur, ring-tailed"},
    {"Animal names":"Stilt, black-winged"},
    {"Animal names":"Beaver, eurasian"},
    {"Animal names":"Bird (unidentified)"},
    {"Animal names":"Galapagos mockingbird"},
    {"Animal names":"Blue-faced booby"},
    {"Animal names":"Four-horned antelope"},
    {"Animal names":"Sheep, stone"},
    {"Animal names":"White-winged tern"},
    {"Animal names":"Bobcat"},
    {"Animal names":"Manatee"},
    {"Animal names":"Sulfur-crested cockatoo"},
    {"Animal names":"Goat, mountain"},
    {"Animal names":"Cockatoo, red-breasted"},
    {"Animal names":"Turtle (unidentified)"},
    {"Animal names":"Duck, comb"},
    {"Animal names":"Long-tailed spotted cat"},
    {"Animal names":"Grey heron"},
    {"Animal names":"Eagle, white-bellied sea"},
    {"Animal names":"Ring-tailed coatimundi"},
    {"Animal names":"Hartebeest, coke's"},
    {"Animal names":"Glider, feathertail"},
    {"Animal names":"Armadillo, seven-banded"},
    {"Animal names":"Crane, wattled"},
    {"Animal names":"Topi"},
    {"Animal names":"Koala"},
    {"Animal names":"Francolin, swainson's"},
    {"Animal names":"Civet (unidentified)"},
    {"Animal names":"Echidna, short-beaked"},
    {"Animal names":"Elephant, african"},
    {"Animal names":"Field flicker"},
    {"Animal names":"Tiger cat"},
    {"Animal names":"Red-breasted cockatoo"},
    {"Animal names":"Armadillo, seven-banded"},
    {"Animal names":"Tiger snake"},
    {"Animal names":"Smith's bush squirrel"},
    {"Animal names":"Mallard"},
    {"Animal names":"Catfish, blue"},
    {"Animal names":"Red-breasted nuthatch"},
    {"Animal names":"Civet, small-toothed palm"},
    {"Animal names":"Eagle, crowned"},
    {"Animal names":"Black-eyed bulbul"},
    {"Animal names":"Heron, green-backed"},
    {"Animal names":"Fisher"},
    {"Animal names":"Lemming, collared"},
    {"Animal names":"Brolga crane"},
    {"Animal names":"Antelope, roan"},
    {"Animal names":"Possum, western pygmy"},
    {"Animal names":"Chuckwalla"},
    {"Animal names":"Long-finned pilot whale"},
    {"Animal names":"Seal, southern elephant"},
    {"Animal names":"Woodcock, american"},
    {"Animal names":"Koala"},
    {"Animal names":"Dove, ring"},
    {"Animal names":"Vulture, bengal"},
    {"Animal names":"White-eye, pale"},
    {"Animal names":"Painted stork"},
    {"Animal names":"Porcupine, crested"},
    {"Animal names":"African clawless otter"},
    {"Animal names":"Moose"},
    {"Animal names":"Western palm tanager (unidentified)"},
    {"Animal names":"Peregrine falcon"},
    {"Animal names":"Stilt, black-winged"},
    {"Animal names":"Weaver, lesser masked"},
    {"Animal names":"Thrasher, curve-billed"},
    {"Animal names":"Field flicker"},
    {"Animal names":"Fox, blue"},
    {"Animal names":"Snake, buttermilk"},
    {"Animal names":"Mongoose, banded"},
    {"Animal names":"Goose, snow"},
    {"Animal names":"Bonnet macaque"},
    {"Animal names":"Long-tailed skua"},
    {"Animal names":"Penguin, magellanic"},
    {"Animal names":"Slender-billed cockatoo"},
    {"Animal names":"Snake, racer"},
    {"Animal names":"Galapagos dove"},
    {"Animal names":"Booby, blue-faced"},
    {"Animal names":"Red lava crab"},
    {"Animal names":"Sloth, two-toed tree"},
    {"Animal names":"Marmot, yellow-bellied"},
    {"Animal names":"African snake (unidentified)"},
    {"Animal names":"Red-tailed cockatoo"},
    {"Animal names":"Elephant, african"},
    {"Animal names":"Macaque, rhesus"},
    {"Animal names":"Duck, mountain"},
    {"Animal names":"River wallaby"},
    {"Animal names":"Eagle, long-crested hawk"},
    {"Animal names":"Lechwe, kafue flats"},
    {"Animal names":"Stork, openbill"},
    {"Animal names":"Red howler monkey"},
    {"Animal names":"Antelope, roan"},
    {"Animal names":"Four-striped grass mouse"},
    {"Animal names":"Gray duiker"},
    {"Animal names":"Mudskipper (unidentified)"},
    {"Animal names":"Pelican, eastern white"},
    {"Animal names":"Kori bustard"},
    {"Animal names":"Vulture, white-headed"},
    {"Animal names":"Blue racer"},
    {"Animal names":"Hoffman's sloth"},
    {"Animal names":"Spotted wood sandpiper"},
    {"Animal names":"Cormorant, flightless"},
    {"Animal names":"Red-tailed hawk"},
    {"Animal names":"Hornbill, southern ground"},
    {"Animal names":"Devil, tasmanian"},
    {"Animal names":"Green-winged macaw"},
    {"Animal names":"Brown brocket"},
    {"Animal names":"Laughing dove"},
    {"Animal names":"Black-cheeked waxbill"},
    {"Animal names":"Little grebe"},
    {"Animal names":"Macaw, green-winged"},
    {"Animal names":"Hedgehog, south african"},
    {"Animal names":"Otter, african clawless"},
    {"Animal names":"Pacific gull"},
    {"Animal names":"Grizzly bear"},
    {"Animal names":"Booby, blue-footed"},
    {"Animal names":"Thrasher, curve-billed"},
    {"Animal names":"Cormorant (unidentified)"},
    {"Animal names":"Vulture, king"},
    {"Animal names":"Coqui francolin"},
    {"Animal names":"Tsessebe"},
    {"Animal names":"Finch, common melba"},
    {"Animal names":"Snake, carpet"},
    {"Animal names":"Mandras tree shrew"},
    {"Animal names":"Deer, savannah"},
    {"Animal names":"Stilt, black-winged"},
    {"Animal names":"Mountain lion"},
    {"Animal names":"Water monitor"},
    {"Animal names":"Margay"},
    {"Animal names":"White-eye, pale"},
    {"Animal names":"Long-billed cockatoo"},
    {"Animal names":"American crow"},
    {"Animal names":"Onager"},
    {"Animal names":"Boa, mexican"},
    {"Animal names":"Openbill stork"},
    {"Animal names":"Hawk, red-tailed"},
    {"Animal names":"Kite, black"},
    {"Animal names":"Booby, blue-faced"},
    {"Animal names":"Turtle, long-necked"},
    {"Animal names":"Zorro, azara's"},
    {"Animal names":"Black-tailed deer"},
    {"Animal names":"Desert tortoise"},
    {"Animal names":"Civet, small-toothed palm"},
    {"Animal names":"Siskin, pine"},
    {"Animal names":"Quoll, spotted-tailed"},
    {"Animal names":"Zorilla"},
    {"Animal names":"Swan, black"},
    {"Animal names":"Hawk, galapagos"},
    {"Animal names":"Collared lemming"},
    {"Animal names":"European badger"},
    {"Animal names":"Roan antelope"},
    {"Animal names":"Dolphin, bottle-nose"},
    {"Animal names":"Quail, gambel's"},
    {"Animal names":"Eastern grey kangaroo"},
    {"Animal names":"Salmon pink bird eater tarantula"},
    {"Animal names":"White-necked stork"},
    {"Animal names":"Mongoose, banded"},
    {"Animal names":"Toucan, white-throated"},
    {"Animal names":"Tortoise, galapagos"},
    {"Animal names":"Python (unidentified)"},
    {"Animal names":"Lemur, lesser mouse"},
    {"Animal names":"Goose, cereopsis"},
    {"Animal names":"Pademelon, red-legged"},
    {"Animal names":"African pied wagtail"},
    {"Animal names":"Cobra (unidentified)"},
    {"Animal names":"Chimpanzee"},
    {"Animal names":"Parrot, hawk-headed"},
    {"Animal names":"Skua, long-tailed"},
    {"Animal names":"Weaver, chestnut"},
    {"Animal names":"Black and white colobus"},
    {"Animal names":"Quail, gambel's"},
    {"Animal names":"Otter, giant"},
    {"Animal names":"Striped dolphin"},
    {"Animal names":"Moorhen, purple"},
    {"Animal names":"Blackbuck"},
    {"Animal names":"Black-crowned night heron"},
    {"Animal names":"Lion, southern sea"},
    {"Animal names":"Horned rattlesnake"},
    {"Animal names":"Giant armadillo"},
    {"Animal names":"Cardinal, black-throated"},
    {"Animal names":"Bird, black-throated butcher"},
    {"Animal names":"Hanuman langur"},
    {"Animal names":"Potoroo"},
    {"Animal names":"American Virginia opossum"},
    {"Animal names":"American badger"},
    {"Animal names":"Fox, savanna"},
    {"Animal names":"Spectacled caiman"},
    {"Animal names":"Red-billed buffalo weaver"},
    {"Animal names":"Brush-tailed bettong"},
    {"Animal names":"Fox, savanna"},
    {"Animal names":"Red-billed hornbill"},
    {"Animal names":"Dingo"},
    {"Animal names":"Bald eagle"},
    {"Animal names":"Red-knobbed coot"},
    {"Animal names":"Grouse, sage"},
    {"Animal names":"White-winged dove"},
    {"Animal names":"Tarantula"},
    {"Animal names":"Viper, egyptian"},
    {"Animal names":"Rufous-collared sparrow"},
    {"Animal names":"Seal, northern fur"},
    {"Animal names":"Teal, hottentot"},
    {"Animal names":"Eastern quoll"},
    {"Animal names":"Goldeneye, common"},
    {"Animal names":"Indian tree pie"},
    {"Animal names":"Cheetah"},
    {"Animal names":"Japanese macaque"},
    {"Animal names":"Bustard, kori"},
    {"Animal names":"Huron"},
    {"Animal names":"Carmine bee-eater"},
    {"Animal names":"Woolly-necked stork"},
    {"Animal names":"Seal, northern elephant"},
    {"Animal names":"Dunnart, fat-tailed"},
    {"Animal names":"Starling, greater blue-eared"},
    {"Animal names":"Cat, miner's"},
    {"Animal names":"Capuchin, black-capped"},
    {"Animal names":"Squirrel, palm"},
    {"Animal names":"Numbat"},
    {"Animal names":"Flycatcher, tyrant"},
    {"Animal names":"Hawk, galapagos"},
    {"Animal names":"Coyote"},
    {"Animal names":"White-winged dove"},
    {"Animal names":"White-necked raven"},
    {"Animal names":"Hippopotamus"},
    {"Animal names":"Frogmouth, tawny"},
    {"Animal names":"Crown of thorns starfish"},
    {"Animal names":"Monkey, rhesus"},
    {"Animal names":"Lava gull"},
    {"Animal names":"Cobra (unidentified)"},
    {"Animal names":"Coatimundi, ring-tailed"},
    {"Animal names":"Marmot, hoary"},
    {"Animal names":"White-eye, pale"},
    {"Animal names":"White-rumped vulture"},
    {"Animal names":"Gazelle, grant's"},
    {"Animal names":"Steller's sea lion"},
    {"Animal names":"Water moccasin"},
    {"Animal names":"Porcupine, crested"},
    {"Animal names":"Arctic ground squirrel"},
    {"Animal names":"Gulls (unidentified)"},
    {"Animal names":"Weaver, lesser masked"},
    {"Animal names":"Godwit, hudsonian"},
    {"Animal names":"Long-nosed bandicoot"},
    {"Animal names":"Macaque, bonnet"},
    {"Animal names":"Lizard, giant girdled"},
    {"Animal names":"Cape Barren goose"},
    {"Animal names":"Bandicoot, short-nosed"},
    {"Animal names":"Mountain duck"},
    {"Animal names":"Two-toed tree sloth"},
    {"Animal names":"Rhinoceros, square-lipped"},
    {"Animal names":"Greylag goose"},
    {"Animal names":"Crested porcupine"},
    {"Animal names":"Common brushtail possum"},
    {"Animal names":"Otter, canadian river"},
    {"Animal names":"Golden brush-tailed possum"},
    {"Animal names":"Scaly-breasted lorikeet"},
    {"Animal names":"Crow, american"},
    {"Animal names":"Brazilian tapir"},
    {"Animal names":"South American meadowlark (unidentified)"},
    {"Animal names":"Bateleur eagle"},
    {"Animal names":"Jaguarundi"},
    {"Animal names":"Asian water buffalo"},
    {"Animal names":"Brazilian tapir"},
    {"Animal names":"Ibex"},
    {"Animal names":"Emerald-spotted wood dove"},
    {"Animal names":"White spoonbill"},
    {"Animal names":"Emerald green tree boa"},
    {"Animal names":"Squirrel, eurasian red"},
    {"Animal names":"Wapiti, elk,"},
    {"Animal names":"Moccasin, water"},
    {"Animal names":"Tortoise, burmese brown mountain"},
    {"Animal names":"White-headed vulture"},
    {"Animal names":"Cockatoo, long-billed"},
    {"Animal names":"Slender-billed cockatoo"},
    {"Animal names":"Lesser masked weaver"},
    {"Animal names":"Quail, gambel's"},
    {"Animal names":"Crimson-breasted shrike"},
    {"Animal names":"Cuis"},
    {"Animal names":"Kingfisher, malachite"},
    {"Animal names":"Goldeneye, barrows"},
    {"Animal names":"Long-crested hawk eagle"},
    {"Animal names":"Brown pelican"},
    {"Animal names":"Coqui francolin"},
    {"Animal names":"Common seal"},
    {"Animal names":"Pied crow"},
    {"Animal names":"Brazilian otter"},
    {"Animal names":"Weaver, lesser masked"},
    {"Animal names":"Red brocket"},
    {"Animal names":"Common dolphin"},
    {"Animal names":"Penguin, magellanic"},
    {"Animal names":"Yellow-bellied marmot"},
    {"Animal names":"Otter, small-clawed"},
    {"Animal names":"Flicker, field"},
    {"Animal names":"Otter, cape clawless"},
    {"Animal names":"Dassie"},
    {"Animal names":"Jackrabbit, white-tailed"},
    {"Animal names":"Honey badger"},
    {"Animal names":"African skink"},
    {"Animal names":"Southern lapwing"},
    {"Animal names":"Badger, european"},
    {"Animal names":"Goldeneye, barrows"},
    {"Animal names":"Duiker, gray"},
    {"Animal names":"Griffon vulture"},
    {"Animal names":"Parrot, hawk-headed"},
    {"Animal names":"Blue-faced booby"},
    {"Animal names":"Brown antechinus"},
    {"Animal names":"Tiger snake"},
    {"Animal names":"Black-necked stork"},
    {"Animal names":"Swamp deer"},
    {"Animal names":"Coot, red-knobbed"},
    {"Animal names":"Chacma baboon"},
    {"Animal names":"Barbet, levaillant's"},
    {"Animal names":"Bustard, kori"},
    {"Animal names":"Cat, african wild"},
    {"Animal names":"Brolga crane"},
    {"Animal names":"Black kite"},
    {"Animal names":"Bonnet macaque"},
    {"Animal names":"Loris, slender"},
    {"Animal names":"Potoroo"},
    {"Animal names":"Spotted hyena"},
    {"Animal names":"Owl, snowy"},
    {"Animal names":"Lizard, frilled"},
    {"Animal names":"Snake (unidentified)"},
    {"Animal names":"Dove, ring"},
    {"Animal names":"Mule deer"},
    {"Animal names":"Malay squirrel (unidentified)"},
    {"Animal names":"Seal, northern elephant"},
    {"Animal names":"Green vine snake"},
    {"Animal names":"Dabchick"},
    {"Animal names":"Greylag goose"},
    {"Animal names":"Crab (unidentified)"},
    {"Animal names":"Possum, common brushtail"},
    {"Animal names":"White-bellied sea eagle"},
    {"Animal names":"Fox, savanna"},
    {"Animal names":"Paca"},
    {"Animal names":"Common palm civet"},
    {"Animal names":"Wild boar"},
    {"Animal names":"Zorro, azara's"},
    {"Animal names":"African jacana"},
    {"Animal names":"Olive baboon"},
    {"Animal names":"Red-headed woodpecker"},
    {"Animal names":"Dog, bush"},
    {"Animal names":"Godwit, hudsonian"},
    {"Animal names":"Green heron"},
    {"Animal names":"Red-shouldered glossy starling"},
    {"Animal names":"Cobra, cape"},
    {"Animal names":"Tsessebe"},
    {"Animal names":"Brush-tailed phascogale"},
    {"Animal names":"Kangaroo, brush-tailed rat"},
    {"Animal names":"Stork, saddle-billed"},
    {"Animal names":"Black curlew"},
    {"Animal names":"Wallaby, agile"},
    {"Animal names":"Sunbird, lesser double-collared"},
    {"Animal names":"Owl, white-browed"},
    {"Animal names":"Tyrant flycatcher"},
    {"Animal names":"Dassie"},
    {"Animal names":"Oryx, beisa"},
    {"Animal names":"Ring-necked pheasant"},
    {"Animal names":"Booby, blue-faced"},
    {"Animal names":"Elegant crested tinamou"},
    {"Animal names":"Sloth, hoffman's"},
    {"Animal names":"Dove, emerald-spotted wood"},
    {"Animal names":"Mountain goat"},
    {"Animal names":"Lesser masked weaver"},
    {"Animal names":"Musk ox"},
    {"Animal names":"Wombat, southern hairy-nosed"},
    {"Animal names":"Trumpeter, green-winged"},
    {"Animal names":"Nuthatch, red-breasted"},
    {"Animal names":"Antelope, sable"},
    {"Animal names":"Cormorant, pied"},
    {"Animal names":"Black-footed ferret"},
    {"Animal names":"Bushpig"},
    {"Animal names":"Bison, american"},
    {"Animal names":"Savannah deer"},
    {"Animal names":"Indian giant squirrel"},
    {"Animal names":"Jabiru stork"},
    {"Animal names":"Stork, saddle-billed"},
    {"Animal names":"Golden-mantled ground squirrel"},
    {"Animal names":"Spotted hyena"},
    {"Animal names":"Sungazer, yellow-brown"},
    {"Animal names":"Common rhea"},
    {"Animal names":"Squirrel, richardson's ground"},
    {"Animal names":"African pied wagtail"},
    {"Animal names":"Lizard, giant girdled"},
    {"Animal names":"Red-breasted cockatoo"},
    {"Animal names":"Otter, brazilian"},
    {"Animal names":"Monkey, bleeding heart"},
    {"Animal names":"Mynah, indian"},
    {"Animal names":"Indian giant squirrel"},
    {"Animal names":"Fork-tailed drongo"},
    {"Animal names":"Macaque, japanese"},
    {"Animal names":"Ant (unidentified)"},
    {"Animal names":"Steenbuck"},
    {"Animal names":"Turkey, wild"},
    {"Animal names":"Black-throated cardinal"},
    {"Animal names":"Deer, barasingha"},
    {"Animal names":"Albatross, waved"},
    {"Animal names":"Phascogale, red-tailed"},
    {"Animal names":"Black-crowned crane"},
    {"Animal names":"Spotted-tailed quoll"},
    {"Animal names":"Butterfly, canadian tiger swallowtail"},
    {"Animal names":"Viper, egyptian"},
    {"Animal names":"Large cormorant"},
    {"Animal names":"South American puma"},
    {"Animal names":"Galapagos tortoise"},
    {"Animal names":"Red-cheeked cordon bleu"},
    {"Animal names":"Black swan"},
    {"Animal names":"Red-breasted cockatoo"},
    {"Animal names":"Openbill, asian"},
    {"Animal names":"Bennett's wallaby"},
    {"Animal names":"Zorilla"},
    {"Animal names":"Lesser flamingo"},
    {"Animal names":"Goose, snow"},
    {"Animal names":"Red-capped cardinal"},
    {"Animal names":"Creeper, black-tailed tree"},
    {"Animal names":"Two-toed sloth"},
    {"Animal names":"Spurfowl, yellow-necked"},
    {"Animal names":"Squirrel, smith's bush"},
    {"Animal names":"Squirrel, uinta ground"},
    {"Animal names":"Squirrel, smith's bush"},
    {"Animal names":"Glider, squirrel"},
    {"Animal names":"Malay squirrel (unidentified)"},
    {"Animal names":"Wallaby, agile"},
    {"Animal names":"Dog, raccoon"},
    {"Animal names":"Dark-winged trumpeter"},
    {"Animal names":"Eurasian hoopoe"},
    {"Animal names":"Green vine snake"},
    {"Animal names":"Snake, buttermilk"},
    {"Animal names":"Crane, stanley"},
    {"Animal names":"Northern elephant seal"},
    {"Animal names":"Coot, red-knobbed"},
    {"Animal names":"Langur, gray"},
    {"Animal names":"Carpet snake"},
    {"Animal names":"White-eye, cape"},
    {"Animal names":"Bird, secretary"},
    {"Animal names":"Oryx, beisa"},
    {"Animal names":"Fox, asian red"},
    {"Animal names":"Toucan, white-throated"},
    {"Animal names":"Monkey, bleeding heart"},
    {"Animal names":"White-nosed coatimundi"},
    {"Animal names":"Kiskadee, great"},
    {"Animal names":"Eagle, white-bellied sea"},
    {"Animal names":"Euro wallaby"},
    {"Animal names":"Cow, scottish highland"},
    {"Animal names":"Bleu, red-cheeked cordon"},
    {"Animal names":"Civet, small-toothed palm"},
    {"Animal names":"Cat, miner's"},
    {"Animal names":"Native cat"},
    {"Animal names":"Lizard, giant girdled"},
    {"Animal names":"Urial"},
    {"Animal names":"Dusky rattlesnake"},
    {"Animal names":"Small-spotted genet"},
    {"Animal names":"Chital"},
    {"Animal names":"African bush squirrel"},
    {"Animal names":"Tiger"},
    {"Animal names":"Frilled dragon"},
    {"Animal names":"Dromedary camel"},
    {"Animal names":"Polecat, african"},
    {"Animal names":"Eastern box turtle"},
    {"Animal names":"Buffalo, wild water"},
    {"Animal names":"Bulbul, african red-eyed"},
    {"Animal names":"Pigeon, feral rock"},
    {"Animal names":"Crab (unidentified)"},
    {"Animal names":"Cheetah"},
    {"Animal names":"Vulture, oriental white-backed"},
    {"Animal names":"Mynah, common"},
    {"Animal names":"Cat, cape wild"},
    {"Animal names":"Emerald green tree boa"},
    {"Animal names":"Starling, superb"},
    {"Animal names":"Barrows goldeneye"},
    {"Animal names":"Timber wolf"},
    {"Animal names":"Monkey, black spider"},
    {"Animal names":"Possum, pygmy"},
    {"Animal names":"Euro wallaby"},
    {"Animal names":"Shrike, crimson-breasted"},
    {"Animal names":"Golden brush-tailed possum"},
    {"Animal names":"Asian false vampire bat"},
    {"Animal names":"Cormorant, flightless"},
    {"Animal names":"Arctic fox"},
    {"Animal names":"Ring-tailed lemur"},
    {"Animal names":"Lemur, lesser mouse"},
    {"Animal names":"Turkey, australian brush"},
    {"Animal names":"Weeper capuchin"},
    {"Animal names":"Possum, ring-tailed"},
    {"Animal names":"Common langur"},
    {"Animal names":"Black bear"},
    {"Animal names":"Ring dove"},
    {"Animal names":"Northern fur seal"},
    {"Animal names":"Common zorro"},
    {"Animal names":"Kongoni"},
    {"Animal names":"Monitor, white-throated"},
    {"Animal names":"Civet (unidentified)"},
    {"Animal names":"Ant (unidentified)"},
    {"Animal names":"Baleen whale"},
    {"Animal names":"Civet, small-toothed palm"},
    {"Animal names":"Lizard, giant girdled"},
    {"Animal names":"Cat, tiger"},
    {"Animal names":"Gray langur"},
    {"Animal names":"Dog, african wild"},
    {"Animal names":"Penguin, little blue"},
    {"Animal names":"Pine siskin"},
    {"Animal names":"Black-winged stilt"},
    {"Animal names":"Small-clawed otter"},
    {"Animal names":"American racer"},
    {"Animal names":"Gerenuk"},
    {"Animal names":"Common green iguana"},
    {"Animal names":"Finch, common melba"},
    {"Animal names":"Ground monitor (unidentified)"},
    {"Animal names":"Admiral, indian red"},
    {"Animal names":"Glider, sugar"},
    {"Animal names":"Crab-eating fox"},
    {"Animal names":"Thrasher, curve-billed"},
    {"Animal names":"Gull, kelp"},
    {"Animal names":"Stanley crane"},
    {"Animal names":"Gull, swallow-tail"},
    {"Animal names":"Dove, little brown"},
    {"Animal names":"Bald eagle"},
    {"Animal names":"Kangaroo, black-faced"},
    {"Animal names":"Ring-tailed coatimundi"},
    {"Animal names":"Duck, comb"},
    {"Animal names":"Tyrant flycatcher"},
    {"Animal names":"Blue duck"},
    {"Animal names":"White-throated robin"},
    {"Animal names":"Flicker, field"},
    {"Animal names":"Blue crane"},
    {"Animal names":"Hummingbird (unidentified)"},
    {"Animal names":"Grant's gazelle"},
    {"Animal names":"Gray rhea"},
    {"Animal names":"Dog, african wild"},
    {"Animal names":"Bee-eater, carmine"},
    {"Animal names":"Shrike, southern white-crowned"},
    {"Animal names":"Owl, madagascar hawk"},
    {"Animal names":"Red-billed buffalo weaver"},
    {"Animal names":"Darwin ground finch (unidentified)"},
    {"Animal names":"Eurasian badger"},
    {"Animal names":"Black vulture"},
    {"Animal names":"Fox, cape"},
    {"Animal names":"Burmese black mountain tortoise"},
    {"Animal names":"Water moccasin"},
    {"Animal names":"Spurfowl, yellow-necked"},
    {"Animal names":"White-winged dove"},
    {"Animal names":"Oriental short-clawed otter"},
    {"Animal names":"Kingfisher, white-throated"},
    {"Animal names":"Crested barbet"},
    {"Animal names":"Skunk, striped"},
    {"Animal names":"Deer, savannah"},
    {"Animal names":"Knob-nosed goose"},
    {"Animal names":"Squirrel, nelson ground"},
    {"Animal names":"Phascogale, red-tailed"},
    {"Animal names":"Mynah, common"},
    {"Animal names":"Oriental short-clawed otter"},
    {"Animal names":"Tammar wallaby"},
    {"Animal names":"American bison"},
    {"Animal names":"Silver gull"},
    {"Animal names":"Macaw, scarlet"},
    {"Animal names":"Goose, cereopsis"},
    {"Animal names":"African fish eagle"},
    {"Animal names":"Turtle, long-necked"},
    {"Animal names":"Constrictor, eastern boa"},
    {"Animal names":"Urial"},
    {"Animal names":"Cook's tree boa"},
    {"Animal names":"Wolf, mexican"},
    {"Animal names":"Giant otter"},
    {"Animal names":"Chickadee, black-capped"},
    {"Animal names":"Ferruginous hawk"},
    {"Animal names":"Bustard, kori"},
    {"Animal names":"Wombat, southern hairy-nosed"},
    {"Animal names":"Egret, cattle"},
    {"Animal names":"Sacred ibis"},
    {"Animal names":"Sloth bear"},
    {"Animal names":"South African hedgehog"},
    {"Animal names":"Asiatic jackal"},
    {"Animal names":"Smith's bush squirrel"},
    {"Animal names":"Iguana, common green"},
    {"Animal names":"Barbet, crested"},
    {"Animal names":"Mourning collared dove"},
    {"Animal names":"Lizard, blue-tongued"},
    {"Animal names":"Leopard"},
    {"Animal names":"Tenrec, tailless"},
    {"Animal names":"Paca"},
    {"Animal names":"Lizard, goanna"},
    {"Animal names":"Langur, gray"},
    {"Animal names":"White-throated monitor"},
    {"Animal names":"Roller, lilac-breasted"},
    {"Animal names":"European red squirrel"},
    {"Animal names":"Two-banded monitor"},
    {"Animal names":"Cow, scottish highland"},
    {"Animal names":"Armadillo, nine-banded"},
    {"Animal names":"Shrike, common boubou"},
    {"Animal names":"Pintail, bahama"},
    {"Animal names":"Beaver, european"},
    {"Animal names":"Curve-billed thrasher"},
    {"Animal names":"Gemsbok"},
    {"Animal names":"Penguin, galapagos"},
    {"Animal names":"Yak"},
    {"Animal names":"Giant heron"},
    {"Animal names":"Bird, pied butcher"},
    {"Animal names":"Black-throated cardinal"},
    {"Animal names":"Francolin, coqui"},
    {"Animal names":"Little brown dove"},
    {"Animal names":"Macaw, green-winged"},
    {"Animal names":"Glider, sugar"},
    {"Animal names":"Sloth, hoffman's"},
    {"Animal names":"Praying mantis (unidentified)"},
    {"Animal names":"Bald eagle"},
    {"Animal names":"Olive baboon"},
    {"Animal names":"Superb starling"},
    {"Animal names":"Common seal"},
    {"Animal names":"Flamingo, chilean"},
    {"Animal names":"Crested screamer"},
    {"Animal names":"South African hedgehog"},
    {"Animal names":"Comb duck"},
    {"Animal names":"Lion, asian"},
    {"Animal names":"Blue crane"},
    {"Animal names":"Hartebeest, coke's"},
    {"Animal names":"Avocet, pied"},
    {"Animal names":"Red-winged blackbird"},
    {"Animal names":"Trotter, lily"},
    {"Animal names":"Sockeye salmon"},
    {"Animal names":"White-necked raven"},
    {"Animal names":"Oriental white-backed vulture"},
    {"Animal names":"Jungle kangaroo"},
    {"Animal names":"Bent-toed gecko"},
    {"Animal names":"Penguin, fairy"},
    {"Animal names":"Dragonfly, russian"},
    {"Animal names":"Deer, barasingha"},
    {"Animal names":"Snake, racer"},
    {"Animal names":"Swallow-tail gull"},
    {"Animal names":"Butterfly (unidentified)"},
    {"Animal names":"Sambar"},
    {"Animal names":"Coatimundi, ring-tailed"},
    {"Animal names":"Penguin, magellanic"},
    {"Animal names":"Owl, great horned"},
    {"Animal names":"Bear, polar"},
    {"Animal names":"Black-necked stork"},
    {"Animal names":"Blue-breasted cordon bleu"},
    {"Animal names":"Blacksmith plover"},
    {"Animal names":"Chacma baboon"},
    {"Animal names":"Kalahari scrub robin"},
    {"Animal names":"Bent-toed gecko"},
    {"Animal names":"Hornbill, leadbeateri's ground"},
    {"Animal names":"Cook's tree boa"},
    {"Animal names":"Thomson's gazelle"},
    {"Animal names":"Pocket gopher (unidentified)"},
    {"Animal names":"African ground squirrel (unidentified)"},
    {"Animal names":"Zebra, common"},
    {"Animal names":"Butterfly, canadian tiger swallowtail"},
    {"Animal names":"Otter, canadian river"},
    {"Animal names":"Shark, blue"},
    {"Animal names":"Possum, common brushtail"},
    {"Animal names":"Barbet, levaillant's"},
    {"Animal names":"Bahama pintail"},
    {"Animal names":"Bare-faced go away bird"},
    {"Animal names":"Possum, ring-tailed"},
    {"Animal names":"Red-winged hawk (unidentified)"},
    {"Animal names":"Gerenuk"},
    {"Animal names":"Bontebok"},
    {"Animal names":"Red-shouldered glossy starling"},
    {"Animal names":"Hawk-eagle, crowned"},
    {"Animal names":"Otter, canadian river"},
    {"Animal names":"California sea lion"},
    {"Animal names":"Seven-banded armadillo"},
    {"Animal names":"Lizard, frilled"},
    {"Animal names":"Cobra, egyptian"},
    {"Animal names":"Bontebok"},
    {"Animal names":"Steenbok"},
    {"Animal names":"Pheasant, common"},
    {"Animal names":"Pie, indian tree"},
    {"Animal names":"Bear, black"},
    {"Animal names":"Tammar wallaby"},
    {"Animal names":"Nyala"},
    {"Animal names":"Rattlesnake, eastern diamondback"},
    {"Animal names":"Kookaburra, laughing"},
    {"Animal names":"Dog, raccoon"},
    {"Animal names":"Oystercatcher, blackish"},
    {"Animal names":"Silver gull"},
    {"Animal names":"Field flicker"},
    {"Animal names":"Hoffman's sloth"},
    {"Animal names":"Black-capped chickadee"},
    {"Animal names":"Chacma baboon"},
    {"Animal names":"Yellow-rumped siskin"},
    {"Animal names":"Green heron"},
    {"Animal names":"Roseat flamingo"},
    {"Animal names":"Jackal, black-backed"},
    {"Animal names":"Red-tailed hawk"},
    {"Animal names":"Common wallaroo"},
    {"Animal names":"Magnificent frigate bird"},
    {"Animal names":"Green heron"},
    {"Animal names":"Rat, white-faced tree"},
    {"Animal names":"Squirrel, richardson's ground"},
    {"Animal names":"Worm snake (unidentified)"},
    {"Animal names":"Sociable weaver"},
    {"Animal names":"Otter, african clawless"},
    {"Animal names":"Macaque, japanese"},
    {"Animal names":"Galapagos penguin"},
    {"Animal names":"Bat, asian false vampire"},
    {"Animal names":"Crow, american"},
    {"Animal names":"Striped dolphin"},
    {"Animal names":"Wallaby, bennett's"},
    {"Animal names":"Cape clawless otter"},
    {"Animal names":"Spoonbill, white"},
    {"Animal names":"Indian jackal"},
    {"Animal names":"Bird, bare-faced go away"},
    {"Animal names":"Racer, blue"},
    {"Animal names":"White spoonbill"},
    {"Animal names":"Azara's zorro"},
    {"Animal names":"Lemming, arctic"},
    {"Animal names":"Gull, kelp"},
    {"Animal names":"Grenadier, purple"},
    {"Animal names":"Kudu, greater"},
    {"Animal names":"Dove, white-winged"},
    {"Animal names":"Wombat, common"},
    {"Animal names":"Sloth bear"},
    {"Animal names":"Stork, yellow-billed"},
    {"Animal names":"Two-toed sloth"},
    {"Animal names":"Pallas's fish eagle"},
    {"Animal names":"Greater flamingo"},
    {"Animal names":"Frilled dragon"},
    {"Animal names":"Western lowland gorilla"},
    {"Animal names":"Barbet, black-collared"},
    {"Animal names":"Duiker, gray"},
    {"Animal names":"Ox, musk"},
    {"Animal names":"Red and blue macaw"},
    {"Animal names":"Legaan, water"},
    {"Animal names":"Tawny frogmouth"},
    {"Animal names":"Common ringtail"},
    {"Animal names":"Collared lemming"},
    {"Animal names":"Porcupine, tree"},
    {"Animal names":"Lemur, brown"},
    {"Animal names":"Four-spotted skimmer"},
    {"Animal names":"Green vine snake"},
    {"Animal names":"American buffalo"},
    {"Animal names":"Turkey, common"},
    {"Animal names":"Lourie, grey"},
    {"Animal names":"Wolf spider"},
    {"Animal names":"Gnu, brindled"},
    {"Animal names":"Elephant, asian"},
    {"Animal names":"Nilgai"},
    {"Animal names":"Snowy owl"},
    {"Animal names":"Squirrel, golden-mantled ground"},
    {"Animal names":"North American beaver"},
    {"Animal names":"Bulbul, black-eyed"},
    {"Animal names":"Rhea, greater"},
    {"Animal names":"Deer, swamp"},
    {"Animal names":"Owl, burrowing"},
    {"Animal names":"Bird, red-billed tropic"},
    {"Animal names":"Python (unidentified)"},
    {"Animal names":"African ground squirrel (unidentified)"},
    {"Animal names":"Peacock, blue"},
    {"Animal names":"Indian tree pie"},
    {"Animal names":"Pale-throated three-toed sloth"},
    {"Animal names":"Snake, green vine"},
    {"Animal names":"Blue-breasted cordon bleu"},
    {"Animal names":"Least chipmunk"},
    {"Animal names":"White-bellied sea eagle"},
    {"Animal names":"Nyala"},
    {"Animal names":"Armadillo, giant"},
    {"Animal names":"Nine-banded armadillo"},
    {"Animal names":"Mudskipper (unidentified)"},
    {"Animal names":"Oriental white-backed vulture"},
    {"Animal names":"Stork, saddle-billed"},
    {"Animal names":"White-mantled colobus"},
    {"Animal names":"Ibis, puna"},
    {"Animal names":"Helmeted guinea fowl"},
    {"Animal names":"Indian star tortoise"},
    {"Animal names":"Eastern diamondback rattlesnake"},
    {"Animal names":"Sage grouse"},
    {"Animal names":"European wild cat"},
    {"Animal names":"Hyena, brown"},
    {"Animal names":"Blackbuck"},
    {"Animal names":"Anteater, giant"},
    {"Animal names":"Australian spiny anteater"},
    {"Animal names":"Dragon, komodo"},
    {"Animal names":"Monitor, white-throated"},
    {"Animal names":"Indian peacock"},
    {"Animal names":"Hornbill, yellow-billed"},
    {"Animal names":"Azara's zorro"},
    {"Animal names":"Black-throated butcher bird"},
    {"Animal names":"Long-necked turtle"},
    {"Animal names":"Black-backed magpie"},
    {"Animal names":"Squirrel, european red"},
    {"Animal names":"Lily trotter"},
    {"Animal names":"Salmon pink bird eater tarantula"},
    {"Animal names":"Spider, wolf"},
    {"Animal names":"Woodcock, american"},
    {"Animal names":"Water legaan"},
    {"Animal names":"Moccasin, water"},
    {"Animal names":"Blesbok"},
    {"Animal names":"Red lava crab"},
    {"Animal names":"Common langur"},
    {"Animal names":"Uinta ground squirrel"},
    {"Animal names":"Arctic tern"},
    {"Animal names":"Ibis, sacred"},
    {"Animal names":"Mouse, four-striped grass"},
    {"Animal names":"Gorilla, western lowland"},
    {"Animal names":"Raccoon, crab-eating"},
    {"Animal names":"Tarantula"},
    {"Animal names":"Possum, golden brush-tailed"},
    {"Animal names":"Sage hen"},
    {"Animal names":"Australian magpie"},
    {"Animal names":"Black-backed jackal"},
    {"Animal names":"Pigeon, wood"},
    {"Animal names":"Dove, rock"},
    {"Animal names":"Gulls (unidentified)"},
    {"Animal names":"Beaver, american"},
    {"Animal names":"Asian red fox"},
    {"Animal names":"Black-cheeked waxbill"},
    {"Animal names":"Porcupine, prehensile-tailed"},
    {"Animal names":"Wallaby, river"},
    {"Animal names":"Mudskipper (unidentified)"},
    {"Animal names":"Bushbaby, large-eared"},
    {"Animal names":"Agama lizard (unidentified)"},
    {"Animal names":"Capuchin, white-fronted"},
    {"Animal names":"Crane, wattled"},
    {"Animal names":"Black spider monkey"},
    {"Animal names":"Crow, house"},
    {"Animal names":"Nile crocodile"},
    {"Animal names":"Starling, superb"},
    {"Animal names":"Tailless tenrec"},
    {"Animal names":"House sparrow"},
    {"Animal names":"North American porcupine"},
    {"Animal names":"Spotted deer"},
    {"Animal names":"Malabar squirrel"},
    {"Animal names":"Woolly-necked stork"},
    {"Animal names":"Penguin, fairy"},
    {"Animal names":"Civet (unidentified)"},
    {"Animal names":"South American puma"},
    {"Animal names":"Goat, mountain"}]
    dbo.collection("animaldb").insertOne(animalobj, function(err, res) {
      if (err) throw err;
      console.log("1 document inserted");
      db.close();
    });
  });